### ISSUE TITLE
openssl_dhparam should trigger notifications only if updated

### ISSUE THREAD

**Issue by dmromanov** [chef-cookbooks/openssl#46]
openssl_dhparam should trigger notifications only if updated.

```
openssl_dhparam '/etc/ssl/dhparam.pem' do
  key_length 4096
  generator 2
  # Bugged: triggers every time even if the file is up to date
  notifies :restart, 'service[nginx]', :delayed
end
```

**Comment by StephenKing** [comment]
same for `openssl_rsa_key`

**Comment by iennae** [comment]
@dmromanov thanks for filing this issue. We're working on a resource rewrite in PR #46 that should resolve this.

**Comment by tas50** [comment]
This is fixed on master and I'll have a release out ASAP
