### ISSUE TITLE
PKCS8 support

### ISSUE THREAD

**Issue by gsaslis** [chef-cookbooks/openssl#50]
### Cookbook version

6.0.0
### Chef-client version

12.13.37 
### Platform Details

[Operating system distribution and release version. Cloud provider if running in the cloud]
### Scenario:

Trying to generate a PKCS8 private key. (Apparently this is the default now for openssl ?). 
### Steps to Reproduce:

Used the following resource:

```
openssl_x509 '/etc/pki/tls/private/logstash-server.pem' do
  common_name 'logs_server_fqdn'
  org 'org_name'
  org_unit 'ELK'
  country 'NO'
  key_length 2048
  key_file '/etc/pki/tls/private/logstash-server.key'
end
```
### Expected Result:

A PKCS8 private key should have been generated.
### Actual Result:

A PKCS1 private key was generated.

**Comment by tas50** [comment]
Looks like pkcs8 never made it in the openssl ruby bindings. There's PKCS7 and PKCS12 bindings.

**Comment by tas50** [comment]
Closing this out as won't fix since openssl doesn't support this in Ruby
