### ISSUE TITLE
undefined method random_password

### ISSUE THREAD

**Issue by jblaine** [chef-cookbooks/openssl#52]
### Cookbook version
6.1.1

### Chef-client version
12.17.44

### Platform Details
Windows Server 2012

### Scenario:
Trying to use the `random_password` mixin and failing

### Steps to Reproduce:
```
include_recipe 'openssl::default'

Chef::Recipe.send(:include, OpenSSLCookbook::RandomPassword)

user 'jenkins' do
  sensitive true
  home "C:\\Users\\jenkins"
  comment 'R701 Jenkins Slave user'
  password random_password
end
```

### Expected Result:
Expecting to not get an error and for the `random_password` method to be called.

### Actual Result:
`undefined method 'random_password'`

**Comment by jblaine** [comment]
Correction: chef-client 12.12.15

**Comment by tas50** [comment]
@jblaine I'm scratching my head here a bit. That seems like it should work, but clearly it doesn't. Can you try updating a single node to Chef 12.19 so we can rule out some weirdness within the chef-client itself.

Also as a side note you shouldn't need openssl::default anymore. It's currently an empty recipe

**Comment by jblaine** [comment]
Chef 12.19.36 works. Weird.

**Comment by tas50** [comment]
Closing this one out, which feels bad, but I'm not sure what else to do honestly.
