### ISSUE TITLE
openssl_rsa_private_key fails due to undefied method "cipher"

### ISSUE THREAD

**Issue by JazminGonzalez-Rivero** [chef-cookbooks/openssl#65]
### Cookbook version
v8.0.0

### Chef-client version
13.6.4

### Platform Details
redhat 7.4 running on kitchen docker container

### Scenario:
create rsa private key 

### Steps to Reproduce:

include_recipe "openssl"
Chef::Recipe.send(:include, OpenSSLCookbook::RandomPassword)

node.normal['my_secure_attribute'] = random_password(length: 50)

openssl_rsa_private_key "#{node['ssl_directory']}/ca.key" do
  key_length 4096
  key_cipher 'des3'
  key_pass node['my_secure_attribute']
end

(ive also tried leaving the cipher out or using the property "cipher" )

### Expected Result:
create private key 

### Actual Result:
had an error: NoMethodError: undefined method `cipher' for Custom resource openssl_rsa_private_key from cookbook openssl

**Comment by tas50** [comment]
Thanks for the report @JazminGonzalez-Rivero I fixed this and released 8.1.0
