### ISSUE TITLE
Issue in running openssl_x509 on windows

### ISSUE THREAD

**Issue by srinivas-anant** [chef-cookbooks/openssl#66]
### Cookbook version
8.1.0

### Chef-client version
Chef client version - 12.19.36

### Platform Details
AWS Windows 2016 Server which is joined to an Active Directory.

### Scenario:
I am running a wrapper IIS Cookbook (https://github.com/Esri/arcgis-cookbook/tree/master/cookbooks/esri-iis) which creates self-signed certificates on the machine. (Will move on to the certificates created by a third party in another phase.) 

### Steps to Reproduce:
A wrapper cookbook which calls the IIS cookbooks and creates a default IIS website and binds the SSL certificate to the site. 

### Expected Result:
The certificates should be created without any issues but they don't seem to be created and part of the error message is: 
`
no mapping between account names and security ids was done
`

### Actual Result:
This is the error message I get when I converge the wrapper cookbook:
```
Generated at 2018-01-04 03:54:06 -0500
Chef::Exceptions::Win32APIError: openssl_x509[c:\chef\cache/my_domain_name.pem] (esri-iis::default line 42) had an error: Chef::Exceptions::Win32APIError: file[c:\chef\cache/my_domain_name.pem] (c:/chef/cache/cookbooks/openssl/resources/x509.rb line 26) had an error: Chef::Exceptions::Win32APIError: No mapping between account names and security IDs was done.
---- Begin Win32 API output ----
System Error Code: 1332
System Error Message: No mapping between account names and security IDs was done.
---- End Win32 API output ----
```

Any help would be really appreciated. Any ideas on how to proceed forward?

**Comment by tas50** [comment]
Should be fixed with this change: https://github.com/chef-cookbooks/openssl/commit/b27cd3c5e4276f216951db8370c8c93a50a99c63

**Comment by srinivas-anant** [comment]
Thank you this worked. 👍
