### ISSUE TITLE
Property overwrites existing method

### ISSUE THREAD

**Issue by zepheiryan** [chef-cookbooks/openssl#67]
### Cookbook version
8.1.0 (has not changed in 8.1.1)

### Chef-client version
12.21.26

### Platform Details
Ubuntu 16.04.3

### Scenario:
Warning-less Chef client run, preparing to upgrade to Chef Client 13.

### Steps to Reproduce:
Make this cookbook a dependency (in order to use the RandomPassword method) of another in a run list.

### Expected Result:
No warnings.

### Actual Result:
Chef client run log includes: WARN: Property `state` of resource `openssl_x509` overwrites an existing method. Please use a different property name. This will raise an exception in Chef 13. (CHEF-11)/var/chef/cache/cookbooks/openssl/resources/x509.rb:12:in `class_from_file'.

which refers to the `:state` property introduced in commit 67911c027b74f275a0aad8de34e0971de4f60d14 as way to provide a value for a certificate setting.

**Comment by er0** [comment]
Created PR #70 renaming state to state_name.
