### ISSUE TITLE
rsa_private_key resource: cipher vs key_cipher

### ISSUE THREAD

**Issue by ctramnitz** [chef-cookbooks/openssl#68]
### Cookbook version
0.8.1

### Scenario:
Using a non-default cipher

### Steps to Reproduce:
Use "cipher aes-256-cbc" in openssl_rsa_private_key resource

### Expected Result:
aes-256-cbc cipher being used instead of default 3des.

### Actual Result:
undefined method "cipher" for resource ...

The documentation states "cipher" but the resource definition has "key_cipher". Either the documentation or the resource definition should be fixed.

**Comment by tas50** [comment]
I updated the readme with the correct property. Thanks for the note
